'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const bubbleTypes=[['body','💪','Body'],['mind','🧠','Mind'],['relationships','❤️','Relationships'],['money','💰','Money'],['work','💼','Work'],['fun','🎮','Fun'],['growth','🌱','Growth'],['life','🫧','Life']];
const n=v=>Number.isFinite(Number(v))?Number(v):0;
function client(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createClient(u,k):null}

export default function Home(){
 const [tab,setTab]=useState('home'),[text,setText]=useState(''),[entries,setEntries]=useState([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('');
 const supabase=useMemo(()=>client(),[]);
 useEffect(()=>{load()},[]);
 async function load(){const local=JSON.parse(localStorage.getItem('bubble_entries')||'[]');if(!supabase){setEntries(local);return}const {data,error}=await supabase.from('bubbles').select('*').order('created_at',{ascending:false}).limit(250);if(error){setEntries(local);setMessage('Cloud is not connected yet, so Bubble is saving on this device.');return}setEntries(data||[])}
 function localSave(next){localStorage.setItem('bubble_entries',JSON.stringify(next));setEntries(next)}
 async function save(){if(!text.trim()||loading)return;setLoading(true);setMessage('');try{const r=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'log',text})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Bubble could not read that.');const rec={id:crypto.randomUUID(),created_at:new Date().toISOString(),raw_text:text.trim(),summary:p.summary||text.trim(),encouragement:p.encouragement||'You checked in. That counts. 🫧',categories:p.categories||['life'],data:p.data||{}};if(supabase){const {data,error}=await supabase.from('bubbles').insert(rec).select().single();if(error)throw error;setEntries(x=>[data,...x]);setMessage('Saved to your Bubble history. 🫧')}else{localSave([rec,...entries]);setMessage('Saved on this device. Add Supabase variables for cloud history.')}setText('')}catch(e){setMessage(e.message||'Something went wrong.')}finally{setLoading(false)}}
 async function ask(){if(!question.trim()||loading)return;setLoading(true);setAnswer('');try{const r=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'query',text:question,history:entries.slice(0,200)})});const j=await r.json();if(!r.ok)throw new Error(j.error);setAnswer(j.answer)}catch(e){setAnswer(e.message)}finally{setLoading(false)}}
 async function del(id){if(supabase)await supabase.from('bubbles').delete().eq('id',id);localSave(entries.filter(e=>e.id!==id))}
 const totals=useMemo(()=>{const today=new Date().toDateString(),es=entries.filter(e=>new Date(e.created_at).toDateString()===today);return es.reduce((a,e)=>{const d=e.data||{};a.calories+=n(d.calories);a.protein+=n(d.protein_g);a.squats+=n(d.squats);a.steps+=n(d.steps);a.minutes+=n(d.workout_minutes);return a},{calories:0,protein:0,squats:0,steps:0,minutes:0,count:es.length})},[entries]);
 const counts=useMemo(()=>{const c={};entries.forEach(e=>(e.categories||[]).forEach(x=>c[x]=(c[x]||0)+1));return c},[entries]);
 return <main className="shell">
  <header><div><div className="eyebrow">ALLI'S LIFE LEARNING BUBBLE</div><h1>Bubble <span>🫧</span></h1></div><div className="avatar">🌸</div></header>
  <nav>{[['home','Home'],['bubbles','Bubbles'],['history','History'],['stats','Stats']].map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{l}</button>)}</nav>
  {tab==='home'&&<><section className="hero card"><p className="soft">Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, Alli.</p><h2>Tell Bubble what's going on.</h2><p>Food, workouts, feelings, spending, work, random thoughts—ramble normally. Bubble will sort it.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="green tea, most of a pork sandwich, walked a mile, did 100 squats... honestly today was a little weird"/><div className="row"><small>Mistakes are data. Growth is the goal.</small><button className="primary" onClick={save} disabled={loading||!text.trim()}>{loading?'Bubble is thinking...':'Add to Bubble'}</button></div>{message&&<div className="message">{message}</div>}</section><section className="stats today"><Stat i="🔥" l="Calories today" v={Math.round(totals.calories)||'—'}/><Stat i="🥚" l="Protein" v={totals.protein?`${Math.round(totals.protein)}g`:'—'}/><Stat i="💪" l="Squats" v={Math.round(totals.squats)||'—'}/><Stat i="🫧" l="Check-ins" v={totals.count}/></section><section><Title t="Recent bubbles" action={()=>setTab('history')}/><Entries entries={entries.slice(0,4)} del={del}/></section></>}
  {tab==='bubbles'&&<section><Heading p="One life. Different views." h="Your Bubbles"/><div className="bubbleGrid">{bubbleTypes.map(([id,i,l])=><button className="bubble" key={id} onClick={()=>setTab('history')}><span>{i}</span><strong>{l}</strong><small>{counts[id]||0} saved moments</small></button>)}</div></section>}
  {tab==='history'&&<section><Heading p="Bubble remembers." h="History"/><div className="ask card"><label>Ask your history anything</label><div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="What did I eat last month?"/><button className="primary" onClick={ask} disabled={loading||!question.trim()}>Ask</button></div>{answer&&<p className="answer">{answer}</p>}</div><Entries entries={entries} del={del}/></section>}
  {tab==='stats'&&<section><Heading p="Big picture, no judgment." h="Your progress"/><div className="stats big"><Stat i="🫧" l="Total check-ins" v={entries.length}/><Stat i="💪" l="Total squats" v={entries.reduce((a,e)=>a+n(e.data?.squats),0).toLocaleString()}/><Stat i="🚶‍♀️" l="Steps logged" v={entries.reduce((a,e)=>a+n(e.data?.steps),0).toLocaleString()}/><Stat i="⏱️" l="Workout minutes" v={Math.round(entries.reduce((a,e)=>a+n(e.data?.workout_minutes),0))}/><Stat i="🍓" l="Calories logged" v={Math.round(entries.reduce((a,e)=>a+n(e.data?.calories),0)).toLocaleString()}/><Stat i="🌱" l="Growth moments" v={counts.growth||0}/></div><div className="quote card">“You do not have to do this perfectly for it to be changing you.”</div></section>}
  <footer>Built with 🫧, stubbornness, and several future “ew”s.</footer>
 </main>
}
function Heading({p,h}){return <div className="heading"><p className="soft">{p}</p><h2>{h}</h2></div>}
function Title({t,action}){return <div className="title"><h3>{t}</h3><button onClick={action}>See all</button></div>}
function Stat({i,l,v}){return <div className="stat card"><span>{i}</span><div><small>{l}</small><strong>{v}</strong></div></div>}
function Entries({entries,del}){if(!entries.length)return <div className="empty card">Your first Bubble is waiting for you. 🫧</div>;return <div className="list">{entries.map(e=><article className="entry card" key={e.id}><div className="top"><div>{(e.categories||['life']).map(c=><span className="chip" key={c}>{c}</span>)}</div><button onClick={()=>del(e.id)}>×</button></div><time>{new Date(e.created_at).toLocaleString([],{dateStyle:'medium',timeStyle:'short'})}</time><h3>{e.summary}</h3><p className="raw">{e.raw_text}</p>{e.encouragement&&<p className="encourage">{e.encouragement}</p>}<Pills d={e.data||{}}/></article>)}</div>}
function Pills({d}){const a=[['🔥',d.calories&&`~${Math.round(d.calories)} cal`],['🥚',d.protein_g&&`~${Math.round(d.protein_g)}g protein`],['💪',d.squats&&`${Math.round(d.squats)} squats`],['🚶‍♀️',d.steps&&`${Math.round(d.steps)} steps`],['⏱️',d.workout_minutes&&`${Math.round(d.workout_minutes)} min`],['💸',d.spending&&`$${n(d.spending).toFixed(2)}`],['🌤️',d.mood]].filter(x=>x[1]);return a.length?<div className="pills">{a.map(([i,v])=><span key={v}>{i} {v}</span>)}</div>:null}
